(function(){'use strict';
var mb=document.getElementById('mobileBtn'),nl=document.getElementById('navLinks');
mb.addEventListener('click',function(){var o=nl.classList.toggle('open');mb.setAttribute('aria-expanded',o);mb.textContent=o?'✕':'☰';});
document.querySelectorAll('.nav-links a').forEach(function(a){a.addEventListener('click',function(){nl.classList.remove('open');mb.setAttribute('aria-expanded','false');mb.textContent='☰';});});
document.getElementById('yr').textContent=new Date().getFullYear();
document.querySelectorAll('.faq-item').forEach(function(item){var q=item.querySelector('.faq-q');q.addEventListener('click',function(){var isOpen=item.classList.contains('open');document.querySelectorAll('.faq-item').forEach(function(f){f.classList.remove('open');f.querySelector('.faq-q').setAttribute('aria-expanded','false');});if(!isOpen){item.classList.add('open');q.setAttribute('aria-expanded','true');}});});
var els=document.querySelectorAll('.reveal');
if('IntersectionObserver' in window){var obs=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target);}});},{threshold:.1,rootMargin:'0px 0px -40px 0px'});els.forEach(function(el){obs.observe(el);});}else{els.forEach(function(el){el.classList.add('visible');});}
var stb=document.getElementById('scrollTopBtn'),ticking=false;
window.addEventListener('scroll',function(){if(!ticking){window.requestAnimationFrame(function(){if(window.scrollY>400){stb.classList.add('visible');}else{stb.classList.remove('visible');}ticking=false;});ticking=true;}});
stb.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'});});
document.querySelectorAll('a[href^="#"]').forEach(function(a){a.addEventListener('click',function(e){var id=this.getAttribute('href');if(id==='#')return;var t=document.querySelector(id);if(t){e.preventDefault();var off=85;var pos=t.getBoundingClientRect().top+window.scrollY-off;window.scrollTo({top:pos,behavior:'smooth'});}});});
var form=document.getElementById('franchiseForm'),sb=document.getElementById('submitBtn'),fm=document.getElementById('formMsg');
var URL='https://script.google.com/macros/s/AKfycbzrjv35IjBhypH8oCLUxcAXsK4WkPTVSQ_2qq7qqYFAs-U_6YAdgfBlUz2mutpJq-k5/exec';
function showMsg(m,t){fm.textContent=m;fm.className='form-msg '+t;fm.style.display='block';}
if(form&&sb){form.addEventListener('submit',function(e){e.preventDefault();var n=document.getElementById('name').value.trim(),em=document.getElementById('email').value.trim(),ph=document.getElementById('phone').value.trim(),ct=document.getElementById('city').value.trim(),st=document.getElementById('state').value,inv=document.getElementById('invest').value,inf=document.getElementById('info').value.trim();if(n.length<3){showMsg('Please enter your full name (min 3 characters).','error');return;}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)){showMsg('Please enter a valid email address.','error');return;}if(!/^\d{10}$/.test(ph)){showMsg('Please enter a valid 10-digit mobile number.','error');return;}if(!ct||!st||!inv){showMsg('Please fill in all required fields.','error');return;}var orig=sb.textContent;sb.disabled=true;sb.textContent='⏳ Submitting...';var d=new URLSearchParams();d.append('applicantName',n);d.append('applicantEmail',em);d.append('phone',ph);d.append('applicantCity',ct);d.append('applicantState',st);d.append('investmentCapacity',inv);d.append('additionalInfo',inf);d.append('submittedAt',new Date().toISOString());fetch(URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:d.toString()}).then(function(){showMsg('✅ Application submitted! We will contact you within 24 hours.','success');form.reset();}).catch(function(){showMsg('❌ Error submitting form. Please try again.','error');}).finally(function(){sb.disabled=false;sb.textContent=orig;setTimeout(function(){fm.style.display='none';},6000);});});}
})();
